//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlPrestigeApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OwlPrestigeEntities : DbContext
    {
        public OwlPrestigeEntities()
            : base("name=OwlPrestigeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<БанковскиеРеквизиты> БанковскиеРеквизиты { get; set; }
        public virtual DbSet<Задачи> Задачи { get; set; }
        public virtual DbSet<ИсполнителиЗадач> ИсполнителиЗадач { get; set; }
        public virtual DbSet<Компании> Компании { get; set; }
        public virtual DbSet<НазначениеЗадач> НазначениеЗадач { get; set; }
        public virtual DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<ПользователиКомпании> ПользователиКомпании { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Сообщения> Сообщения { get; set; }
        public virtual DbSet<СтатусыЗадач> СтатусыЗадач { get; set; }
        public virtual DbSet<ТипыОбъектов> ТипыОбъектов { get; set; }
    }
}
