//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlPrestigeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class БанковскиеРеквизиты
    {
        public int IDРеквизита { get; set; }
        public int IDПользователя { get; set; }
        public string НомерСчета { get; set; }
        public string НазваниеБанка { get; set; }
        public string АдресБанка { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
