//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlPrestigeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Задачи()
        {
            this.ИсполнителиЗадач = new HashSet<ИсполнителиЗадач>();
            this.НазначениеЗадач = new HashSet<НазначениеЗадач>();
            this.Сообщения = new HashSet<Сообщения>();
        }
    
        public int IDЗадачи { get; set; }
        public string НазваниеЗадачи { get; set; }
        public int IDТипаОбъекта { get; set; }
        public Nullable<System.DateTime> СрокВыполнения { get; set; }
        public int IDСтатуса { get; set; }
        public int IDКомпании { get; set; }
        public byte[] ФайлЧертежа { get; set; }
        public byte[] ФайлСпецификации { get; set; }
        public string Название_объекта { get; set; }
    
        public virtual Компании Компании { get; set; }
        public virtual СтатусыЗадач СтатусыЗадач { get; set; }
        public virtual ТипыОбъектов ТипыОбъектов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсполнителиЗадач> ИсполнителиЗадач { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<НазначениеЗадач> НазначениеЗадач { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сообщения> Сообщения { get; set; }
    }
}
