//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlPrestigeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПаспортныеДанные
    {
        public int IDПаспорта { get; set; }
        public int IDПользователя { get; set; }
        public string СерияПаспорта { get; set; }
        public string НомерПаспорта { get; set; }
        public Nullable<System.DateTime> ДатаВыдачи { get; set; }
        public string МестоВыдачи { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
