//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwlPrestigeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сообщения
    {
        public int IDСообщения { get; set; }
        public int IDЗадачи { get; set; }
        public int IDОтправителя { get; set; }
        public int IDПолучателя { get; set; }
        public string ТекстСообщения { get; set; }
        public byte[] Вложение { get; set; }
        public Nullable<System.DateTime> ВремяОтправки { get; set; }
    
        public virtual Задачи Задачи { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
    }
}
